version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ConnectionStrings__TimeSheetContext=Data Source=sql-server-database; Initial Catalog=TimeSheets; User Id=sa; Password=1AvenueCodePassword*
    volumes:
      - ./Timesheets:/api
    working_dir: /api
    depends_on:
      - sql-server-database
    command: "dotnet run"
    ports:
      - "8001:8081"
  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1AvenueCodePassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ConnectionStrings__TimeSheetContext=Data Source=sql-server-database; Initial Catalog=TimeSheets; User Id=sa; Password=1AvenueCodePassword*
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command:
      [
        "./Scripts/wait-for-it.sh",
        "sql-server-database:1433",
        "--",
        "dotnet",
        "test",
        "../test/Timesheets.Tests.csproj"
      ]
    depends_on:
      - sql-server-database